import{a as p,S as w,i as n}from"./assets/vendor-BjRz3xa9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const g of o.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&f(g)}).observe(document,{childList:!0,subtree:!0});function l(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function f(t){if(t.ep)return;t.ep=!0;const o=l(t);fetch(t.href,o)}})();const v="32675885-ded1f22898004e0649ebaa6fc";p.defaults.baseURL="https://pixabay.com/api/";async function m(r,e){return await p.get(`?key=${v}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${e}`)}const h={galleryEl:document.querySelector(".gallery")};function y(r){const e=$(r);h.galleryEl.insertAdjacentHTML("beforeend",e),E.refresh()}function S(){h.galleryEl.innerHTML=""}function $(r){return r.map(e=>`
        <li class="gallery-item">
          <div class="image-container">
            <a class="gallery-link" href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" /></a>
          </div>
          <div class="info-container">
            <ul class="img-desc">
              <li><strong>Likes:</strong> ${e.likes}</li>
              <li><strong>Views:</strong> ${e.views}</li>
              <li><strong>Comments:</strong> ${e.comments}</li>
              <li><strong>Downloads:</strong> ${e.downloads}</li>
            </ul>
          </div>
        </li>
      `).join("")}let E;E=new w(".gallery a",{captionsData:"alt",captionDelay:250});const s={formEl:document.querySelector(".form"),inputEl:document.querySelector(".input-value"),loadingEl:document.querySelector(".loading"),loadMoreEl:document.querySelector(".btn-load-more")};let c="",i=1,d=0;function L(){s.loadingEl.style.display="block"}function u(){s.loadingEl.style.display="none"}function b(){s.loadMoreEl.classList.remove("btn-load-more-hidden")}function a(){s.loadMoreEl.classList.add("btn-load-more-hidden")}s.formEl.addEventListener("submit",async r=>{if(r.preventDefault(),i=1,c=s.inputEl.value.trim(),!c){n.error({title:"Error",message:"❌ Please enter a search term!",position:"topRight"});return}S(),L();try{const e=await m(c,i);u(),d=Math.ceil(e.data.totalHits/15),e.data.hits.length===0&&s.inputEl.value!==""?n.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(e.data.hits),d>1&&b())}catch{a(),u(),n.error({title:"Error",message:"❌ Something went wrong!",position:"topRight"})}});s.loadMoreEl.addEventListener("click",async()=>{if(i>=d){a(),n.error({title:"Error",message:"❌ We're sorry, but you've reached the end of search results.",position:"topRight"});return}L(),a(),i++;try{const r=await m(c,i);u(),y(r.data.hits);const e=document.querySelector(".gallery-item");if(e){const l=e.getBoundingClientRect().height;window.scrollBy({top:l*2,behavior:"smooth"})}i<d?b():(a(),n.error({title:"Error",message:"❌ We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a(),u(),n.error({title:"Error",message:"❌ Something went wrong!",position:"topRight"})}});
//# sourceMappingURL=index.js.map
